server:
  port: 10000

dubbo:
  application:
    name: boot-dubbo-provider
  # 单注册中心
  registry:
    address: 192.168.52.128:2181
    register: true
    timeout: 10000
    protocol: zookeeper # zookeeper 注册中心